name: fake_store_api
description: Aplicativo que consome uma API fake.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  intl: ^0.19.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  sqflite: ^2.3.0
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.0+4
  path_provider: ^2.1.1
  flutter_screenutil: ^5.9.0
  connectivity_wrapper: ^1.1.4
  animated_text_kit: ^4.2.2
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.6
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.7.1
  melos: ^4.1.0

flutter:

  uses-material-design: true

  assets:
   - assets/

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
